exclude: [README.md]
# Required & Optional Header and Footer Elements used in _layouts/default.html
title: Your Logo and Site Title
description: Describing What You Do
# Update with your github userid and repo name
url: https://TR-Systems.github.io/modernist/
# Optional Header Elements
# logo is 36x36 icon to left of title, with description below
logo: images/logo-github.png
# Optional links in the upper right corner of the header
# Two lines only, keep text and words short to fit in box, use <br> to force break
# Update with your userid and repo name
about_url: https://TR-Systems.github.io/modernist/about.html
about_text: About<br>Your Site
hlink1_url: https://TR-Systems.github.io/modernist/
hlink1_text: Link to<br>Somewhere
# Three lines for Footer Content
# Do not publish email addresses, you will be spammed beyond belief.
# First line of footer
contact_info1: <strong>Contact:</strong>
contact_info2: <em>trsystems.help</em> at the little G mail place.
# Second line
footer_text1: Website powered by Github Pages using modified Modernist Theme
footer_text2: <em>Use my template and get started today!</em>
footer_url: https://github.com/TR-Systems/modernist
# Last line
copyright: Copyright yyyy Your Name, Your Location
